#!/usr/bin/env ruby

require 'apipie-bindings'
require 'rest-client'
require 'optparse'
require 'thread'
require 'json'
require 'yaml'
require 'csv'
require 'pp'

require_relative 'lib/sso'
require_relative 'lib/cache'
require_relative 'lib/api_handler'
require_relative 'lib/option_parser'
require_relative 'lib/subscriptions'

# force the output to be sent to stdout in a sync way
$stdout.sync = true
$options = {}
# build the options parser of the command
globalParser = SSOOptionParser::Builder::initializeGlobalParser
# parsing the options passed
SSOOptionParser::Parser::parse globalParser, ARGV
puts "\n\nJust before start this are the Options:"
pp $options

SSOAPI::Handler::bindAPI

SSOSubscriptions::Fetcher::parseSubscriptions
### NEXT STEP ###
# - subscription retrieveal and collecting
# => read yaml file
# => aggregate data
#
# - density check
# => collecting hypervisor data
# => mapping cluster / number of guests
# => wrote all the csv data
#
# - search hosts
# => build search options
# => search for hosts

# - subscribe hosts
# => get hosts type
# => retrieve hosts full data, in case of hypervisors also facts
# => subscription flow
# => report

### SUBSCRIPTION FLOW ###
# - Hypervisor
# => check empty_hypervisor
# => facts check
# => subscribe hypervisor guests
# - VM
# => facts check
# => check for vdc subs
# - Physical
# => facts check
